# Generated by Django 5.0 on 2023-12-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('visi', models.BooleanField()),
                ('pf', models.CharField(max_length=1)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('visi', models.BooleanField()),
                ('pf', models.CharField(max_length=1)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('thumbnail', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tviews', models.PositiveIntegerField()),
                ('tlikes', models.PositiveIntegerField()),
                ('slug', models.CharField(max_length=25)),
                ('source', models.CharField(max_length=250)),
            ],
        ),
    ]
