# Generated by Django 5.0 on 2023-12-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_remove_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
