# Generated by Django 4.0.5 on 2023-08-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_field', models.CharField(max_length=100)),
                ('y_field', models.IntegerField()),
            ],
        ),
    ]
