# Generated by Django 4.0.5 on 2023-06-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=70)),
                ('lastname', models.CharField(max_length=70)),
                ('username', models.EmailField(max_length=30)),
                ('state', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('phoneNo', models.PositiveIntegerField(max_length=11)),
            ],
        ),
    ]
